### ISSUE TITLE
ADD  -=Gaydayz=- Where Community Matters.

### ISSUE THREAD

**Issue by Truthslayur** [jshwlkr/queersplaygames#18]
Discords fastest growing LGBT friendly community!
![608381939e294ac3b29f0f19f3efb114](https://cloud.githubusercontent.com/assets/13756359/19059787/9c69ff0a-89b0-11e6-8c96-c839d96d4a97.png)

With voice channels for nearly anything you can think of, and text channels for anything your heart desires. We plan on taking advantage of everything Discord has to offer to further create a bigger and better community. We are open to everyone and anyone looking to find a place to be themselves, hang out and make friends. We game, we do Karaoke, movie nights, and more.

**Comment by jshwlkr** [comment]
Links?

**Comment by Vorpalowl** [comment]
Hey @jshwlkr,

We are so sorry about this incredibly late reply!   Unfortunately the notification was lost in all the shuffle at the time.  Anyway - without further delay..., here is discord server link:

https://discord.gg/uGT7eJD

Thanks so much!
Vorpal

**Comment by jshwlkr** [comment]
Added!
