### ISSUE TITLE
Please add Transmission Gaming Discord

### ISSUE THREAD

**Issue by Nikatine** [jshwlkr/queersplaygames#19]
Transmission Gaming is a discord server comprised of transgender gamers. The group holds online gaming events and provides a meetup for other multiplayer gamers who also happen to be trans. 

From Transmission Gaming: 

"Transmission Gaming is an online gaming community comprised solely of trans-identified people. We play competitively and casually in a number of games, such as Overwatch and CS:GO. Our community fosters ambition, acceptance, and camaraderie among the trans community."

https://discord.gg/UmE3TN9

**Comment by jshwlkr** [comment]
Added!
